---
title: "About Me"
editor: visual
---

Broadly, my research aims to understand basic mechanisms that support children’s early learning and their application to real-world learning environments. One component of my research program concerns the development of trust in early childhood. I conduct basic research to understand how children’s trust impacts learning from different informational sources (e.g., caregivers, teachers) as well as how technology use during interactions impacts trust and learning. Complimentary to this line of work, I investigate how playful learning pedagogies serve to facilitate trust and support the development of social-cognitive skills that lead to strong learning outcomes. I aim to translate my research to practice in culturally responsive ways using community-based participatory research methodologies. Through a transdisciplinary approach, I involve communities as active collaborators in my research to ensure children have equitable access to high-quality, culturally responsive learning opportunities in public and educational spaces.

My work has been published in peer-reviewed scientific journals such as *Frontiers in Psychology - Educational Psychology, Early Education and Development, Frontiers in Psychology - Cognitive Psychology, Monographs of the Society for Research in Child Development, Journal of Experimental Child Psychology, PLOSone,* and *Current Directions in Psychology.* I have authored several book chapters on trust in testimony and playful learning.

I am dedicated to increasing the accessibility of my research to communities and stakeholders. I have written blog posts and served on community-facing panels for the Brookings Institution and the Children’s Museum of Tacoma-WA about ways to create child and youth-centered communities. I have also written non-technical papers for the LEGO Foundation, the OECD, and Elements Ed.
