---
title: "Research Projects"
editor: visual
---

**Playful learning landscapes in Santa Ana, CA:** I work closely with collaborators at the University of California, Irvine to bring playful learning landscapes to a predominately Spanish-speaking community in Santa Ana, CA. Using community-based participatory design and participatory action research practices, we created a series of playful installations that will be installed in several community spaces (parks, bus stops, and a grocery store) later this year. We are collecting observational and survey data to understand how the activities impact caregiver-child interactions and neighborhood well-being.

**Playful learning landscapes in early childcare centers in Philadelphia, PA**: With colleagues at the Temple Infant and Child Laboratory, we are infusing ECE settings with playful learning activities that foster early STEM and literacy learning. Activities were co-designed with educators and community members. We are investigating how the activities impact learning and classroom quality using individual student assessments, naturalistic observations, and teacher surveys.

**Perceptions of Storytime.** We are investigating how interactions interrupted by technology (*technoference*) impact preschool-aged children's selective trust and learning. Findings will provide initial evidence regarding the impact of technology use during contingent social interactions.
