---
title: "News"
editor: visual
---

-   Dr. Pesch discusses the newly launched Playful Learning Landscapes Certification Program, which will make it easier for organizations to connect with each other and families to find playful learning spaces in their community. Learn more about the program [here](https://playfullearninglandscapes.com/certification/).

-   Dr. Pesch featured as a speaker and panelist at Greentrike's Symposium "Building a child and youth centered community" where she offers new ways to engage with communities to create playful learning opportunities. You can watch a recording of the [session](https://youtu.be/Eq_v2K6e6nM?t=2) and [panel](https://www.youtube.com/watch?v=bhlzPbfmNYg) on Youtube!

-   Dr. Pesch featured as a panel speaker at the Brookings Institution's event "Fostering community and measuring impact: What's working in playful learning cities" where she highlights ways that communities are being engaged in California. Access the full recording [here](https://www.youtube.com/live/NbDHHUXfof4?feature=share&t=7).

-   Dr. Pesch and her colleagues wrote a blog about the importance of teaching in ways that reflect how human brains learn best. The post was published by the Brookings Institution. Read the full article: <https://www.brookings.edu/articles/what-if-teaching-mirrored-how-human-brains-learn/>

-   Dr. Pesch interviewed by the University of Minnesota's CEHD-Connect magazine for her involvement with the [Young Scientists Mentoring Program](https://icd.umn.edu/outreach/young-scientists/). Read the article full article and learn more about the program: <https://connect.cehd.umn.edu/instilling-the-love-of-scientific-inquiry/>
