---
title: "Publications"
editor: visual
---

## 2023

**Pesch, A.,** & Hirsh-Pasek, K. (In press). Social-emotional development: When soft skills become the hard skills. OECD Publishing, Paris.

DeAngelis, E., Glaspie, N., Bisla, I., **Pesch, A.,** & Koenig, M. A. (in press). Understanding the vulnerability of testimony: Epistemic and interpersonal risks. To appear in K. J. Rotenberg (Eds.), *The Handbook of Trust and Social Psychology*. Edward Elgar Publishing Limited.

Bermudez, V. N., Salazar, J., Garcia, L., Ochoa, K. D., **Pesch, A**., Roldan, W., Soto-Lara, W., Gomez, W., Rodriguez, R., Hirsh-Pasek, K., Ahn, J., & Bustamante, A. S. (2023). Designing culturally situated playful environments for early STEM learning with a Latine community. *Early Childhood Research Quarterly,* 1-12. \[[online](https://www.sciencedirect.com/science/article/pii/S0885200623000807)\]

Fabricius, W. V., Gonzales, C. R., **Pesch, A.**, & Weimer, A. A. (2023). Perceptual Access Reasoning: What are the alternatives? *Cognitive Development, 66,* 101306*.* \[[online](https://www.sciencedirect.com/science/article/pii/S0885201423000114)\]

## 2022

**Pesch, A.,** Ochoa, K. D, Fletcher, K., Bermudez, V. N., Todaro, R., Salazar, J., Gibbs, H. M., Ahn, J., Bustamante, A. S., & Hirsh-Pasek, K. (2022). Reinventing the public square and early educational settings through culturally informed, community co-design: Playful Learning Landscapes. *Frontiers in Psychology - Educational Psychology, 13,* 7322*.* \[[online](https://www.frontiersin.org/articles/10.3389/fpsyg.2022.933320)\]

**Pesch, A.**, Ridge, K. E., Suárez, S., McMyler, B., & Koenig, M. A. (2022). Evaluations of epistemic and practical reasons for belief in a predominately White, US sample of preschoolers. *Journal of Experimental Child Psychology, 223*, 105499. \[[online](https://www.sciencedirect.com/science/article/pii/S002209652200128X)\]

## 2021

**Pesch, A.,** & Koenig, M. A. (2021). Trust Matters: Measuring and identifying a role for epistemic and interpersonal trust in preschoolers' learning from teachers. *Early Education and Development,* 1-26*.* \[[online](https://www.tandfonline.com/doi/abs/10.1080/10409289.2021.1991729)\]

Fabricius, W. V., Gonzales, C.R., **Pesch, A.,** Carroll, K., Weimer, A. A., Pugliese, J., Bolnick, R. R., Kupfer, A., Eisenberg, N., & Spinrad, T. (2021). Perceptual Access Reasoning (PAR) in Developing a Representational Theory of Mind. *Monographs of the Society for Research in Child Development, 86*(3), 7-154. \[[online](https://srcd.onlinelibrary.wiley.com/doi/full/10.1111/mono.12432)\]

## 2020

**Pesch, A.,** Semenov, A. D., & Carlson, S. M. (2020). The path to fully representational Theory of Mind: Conceptual, Executive, and Pragmatic Challenges. *Frontiers in Psychology - Cognitive Science, 11,* 3020. \[[online](https://www.frontiersin.org/articles/10.3389/fpsyg.2020.581117/full)\]

Li, P. H., **Pesch, A.**, Koenig, M. A. (2020). The sense of obligation in children's testimonial learning. *Behavioral and Brain Sciences, 43.* \[[online](https://www.proquest.com/openview/1bff12c40b889608e59ebcc1e7ddd2e2/1?pq-origsite=gscholar&cbl=47829)\]

## 2018

**Pesch, A.,** & Koenig, M. A. (2018). Varieties of trust in preschoolers' learning and practical decisions*. PLOS One, 13*(8). \[[online](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0202506)\]

Ridge, K.E., **Pesch, A**., Suárez, S., & Koenig, M.A. (2018). Insights into children's testimonial reasoning. In P. Ganea and M. Saylor (Eds.), *Language and Concept Development from Infancy Through Childhood: Social Motivation, Cognition, and Linguistic Mechanisms of Learning*. New York, NY: Springer. \[[online](https://link.springer.com/chapter/10.1007/978-3-319-77182-3_8)\]

## 2017

**Pesch, A.,** Suárez, S., & Koenig, M. A. (2017). Trusting Others: Shared reality in testimonial learning. *Current Opinion in Psychology, 23*, 38-41*.* \[[online](https://www.sciencedirect.com/science/article/pii/S2352250X17302270)\]

## 2016

Lin, A. R., Ettekal, A., Simpkins, S., Menjivar, C., Gaskin, E., & **Pesch, A.** (2016). "They will post a law about playing soccer" and other ethnic/racial microaggressions in organized activities experienced by Mexican-Origin families. *Journal of Adolescent Research, 31,* 557-581. \[[online](https://journals.sagepub.com/doi/abs/10.1177/0743558415620670)\]
