---
title: "Teaching"
editor: visual
---

*My approach to teaching draws on my program of research, which aims to create impactful learning environments for children and families from underserved and minoritized communities. My research advocates for children\'s learning through play and argues that relationships are the foundation of strong learning outcomes. Playful learning is not just for kids -- it\'s also a powerful pedagogical approach for teaching at the university level. My teaching goals are thus reflective of active learning, discovery-based learning, or flipped classroom pedagogies that reduce the amount of time spent lecturing in favor of hands-on activities. I believe students learn best when they can form strong interpersonal connections with their peers and instructors. I aim to instill these values and practices in all courses I teach.*

**Arizona State University, Instructor**

Major and Career Exploration (Fall 2020, 20 students, hybrid instruction)

**University of Minnesota, Instructor**

Language Development and Communication (Spring 2019, 65 students)

Introduction to Child Psychology (Spring 2018, 20 students)

**University of Minnesota, Teaching Assistant**

Cognitive Development (Fall 2018)

Language Development and Communication (Spring 2017)

Introduction to Child Psychology (Fall 2016)

Perceptual Development (Fall 2016, Fall 2017)
